basePath: /
host: localhost:8080
info:
  contact: {}
  description: This API is designed to provide a seamless integration of location
    and weather information
  license:
    name: Luiz Palmieri
  title: 'Labs challenge: Deploy Cloud Run'
  version: "1.0"
paths:
  /temperature/{cep}:
    get:
      consumes:
      - application/json
      description: This API is designed to provide a seamless integration of location
        and weather information
      parameters:
      - description: cep
        in: path
        name: cep
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: successful response
          schema:
            type: string
        "404":
          description: can not find zipcode
          schema:
            type: string
        "422":
          description: invalid zipcode
          schema:
            type: string
      summary: GetTemperature
      tags:
      - temperature
swagger: "2.0"
